FROM alpine:latest

ADD . /
WORKDIR /prod

# Install node
# Install Bower
# Install node & bower depends
# Set bower root allow
RUN apk add --update nodejs git nodejs-npm gcc autoconf automake && \
    npm install -g bower && \
    echo '{ "allow_root": true }' > /root/.bowerrc && \
    git config --global url."https://".insteadOf git://
#RUN ls 
#RUN npm install 
#RUN bower install 
RUN apk del gcc autoconf automake && \
   rm -rf /var/cache/apk/* /tmp/*
