FROM alpine:latest

COPY Basic /prod
WORKDIR /prod
RUN apk add --update nodejs git && \
    npm install --global bower && \
    git config --global url."https://".insteadOf git:// && \ 
    npm install --global gulp@3.9.0 && \
    echo '{ "allow_root": true }' > /root/.bowerrc && \
    npm install && \
    bower install && \
    apk del nodejs git --purge 

RUN bower --v
RUN gulp --v
RUN npm --v



